In [89]:
import numpy as np

In [90]:
randoms = np.random.rand(6,5)

In [91]:
randoms

array([[0.32192681, 0.96928969, 0.03672553, 0.54675518, 0.95974696],
       [0.41073718, 0.72172563, 0.38544511, 0.18553664, 0.28157302],
       [0.66414288, 0.29283756, 0.81225252, 0.41282262, 0.49056216],
       [0.88779831, 0.29759764, 0.34830492, 0.885541  , 0.67848858],
       [0.93800973, 0.73157676, 0.15335788, 0.43777891, 0.76518401],
       [0.87860665, 0.33068585, 0.85769666, 0.95549668, 0.88880747]])

In [92]:
randoms = randoms[0]

In [93]:
randoms

array([0.32192681, 0.96928969, 0.03672553, 0.54675518, 0.95974696])

In [94]:
randoms[:2][4:]

array([], dtype=float64)

In [95]:
randoms[2:,:4]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [96]:
randoms[:2,4:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [97]:
randoms[2:]

array([0.03672553, 0.54675518, 0.95974696])

In [98]:
randoms[:2]

array([0.32192681, 0.96928969])

In [99]:
X = np.array([[1,2],[3,4]])
Y = np.array([[5,6],[7,8]])

In [100]:
X.shape

(2, 2)

In [102]:
Y.shape

(2, 2)

In [103]:
X+Y

array([[ 6,  8],
       [10, 12]])

In [104]:
np.add(X,Y)

array([[ 6,  8],
       [10, 12]])

In [105]:
np.subtract(X,Y)

array([[-4, -4],
       [-4, -4]])

In [106]:
np.multiply(X,Y)

array([[ 5, 12],
       [21, 32]])

In [107]:
X*Y

array([[ 5, 12],
       [21, 32]])

In [110]:
# For Matrix Multiplication
np.matmul(X,Y)

array([[19, 22],
       [43, 50]])

In [111]:
X@Y

array([[19, 22],
       [43, 50]])

In [113]:
#'?' will tell what the particular function do

In [114]:
a= []
for i in range(100):
    a.append(i)

In [116]:
a = np.array(a)

In [117]:
type(a)

numpy.ndarray

In [118]:
# Matrix->
b= [[1,2,3,4,5],[6,7,8,9,0]]

In [119]:
b

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]]

In [120]:
c=[]
type(c)

list

In [122]:
np.divide(X,Y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [123]:
X/Y

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [124]:
np.sqrt(X)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [126]:
np.add?

Signature:       np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\prajwal\appdata\local\programs\python\python312\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
   

In [128]:
np.dot(X,Y)
# will be like matrix multiplication

array([[19, 22],
       [43, 50]])

In [141]:
# Dot Product work as same as matrix multiplication

In [129]:
X.dot(Y)

array([[19, 22],
       [43, 50]])

In [136]:
# Flatten give copy of list whereas ravel generate new list 

In [131]:
arr = np.array([[1,2,3],[4,5,6]])

In [137]:
flattened = arr.flatten()         # creates and return a copy of memory

In [133]:
flattened

array([1, 2, 3, 4, 5, 6])

In [138]:
ravelled = arr.ravel()           # changes affect the original array

In [135]:
ravelled

array([1, 2, 3, 4, 5, 6])

In [139]:
# Ravel is faster than flatten

In [140]:
# If arr is store in #100 memory, so ravel will store in #100 memory where as flatten will store in #105 memory

In [143]:
# stack
# randint
# ones, zeroes
# min, max, mean
# average
# std

In [144]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

In [147]:
b= b**2  # All values inside b will be squared

In [146]:
b

array([ 1,  4,  9, 16, 25])

In [162]:
# STACK
#Pasting 1 array over the other -> Stack

In [152]:
np.stack((a,b), axis = 0), np.stack((a,b), axis = 0).shape  # Will align as row

(array([[  1,   2,   3,   4,   5],
        [  1,  16,  81, 256, 625]]),
 (2, 5))

In [153]:
np.stack((a,b), axis = 1), np.stack((a,b), axis = 1).shape    # Will align as column

(array([[  1,   1],
        [  2,  16],
        [  3,  81],
        [  4, 256],
        [  5, 625]]),
 (5, 2))

In [157]:
# Now

In [154]:
a = np.stack((a,b), axis = 0)

In [155]:
a

array([[  1,   2,   3,   4,   5],
       [  1,  16,  81, 256, 625]])

In [156]:
a.shape

(2, 5)

In [158]:
a.reshape(1,10)  # Will reshape in (2*5) = 10 (in multiples of 10)

array([[  1,   2,   3,   4,   5,   1,  16,  81, 256, 625]])

In [159]:
a.reshape(10,1)

array([[  1],
       [  2],
       [  3],
       [  4],
       [  5],
       [  1],
       [ 16],
       [ 81],
       [256],
       [625]])

In [160]:
a.reshape(5,2)

array([[  1,   2],
       [  3,   4],
       [  5,   1],
       [ 16,  81],
       [256, 625]])

In [163]:
# RANDINT

In [184]:
a = np.random.rand()
a 
# Will generate a Random Number

0.7848892181321379

In [183]:
b = np.random.rand(1)
b
# Will Generate a random number in array

array([0.99416579])

In [185]:
x = np.random.randint?

Signature: np.random.randint(low, high=None, size=None, dtype=<class 'int'>)
Docstring:
randint(low, high=None, size=None, dtype=int)

Return random integers from `low` (inclusive) to `high` (exclusive).

Return random integers from the "discrete uniform" distribution of
the specified dtype in the "half-open" interval [`low`, `high`). If
`high` is None (the default), then results are from [0, `low`).

.. note::
    New code should use the `~numpy.random.Generator.integers`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
low : int or array-like of ints
    Lowest (signed) integers to be drawn from the distribution (unless
    ``high=None``, in which case this parameter is one above the
    *highest* such integer).
high : int or array-like of ints, optional
    If provided, one above the largest (signed) integer to be drawn
    from the distribution (see above for behavior if ``high=None``).
    If array-lik

In [190]:
x = np.random.randint(10,20,3) # Between 10 and 20 and the number of elements is 3, Gives a Random Integer where 20 is upper, 10 is the lower limit

In [191]:
x

array([14, 15, 18], dtype=int32)

In [192]:
y = np.random.randint(10,20,10)

In [193]:
y

array([18, 13, 10, 13, 18, 13, 18, 14, 15, 16], dtype=int32)

In [202]:
choice = np.random.choice(x)  # Will take a random number from x

In [203]:
choice

np.int32(15)

In [204]:
# ONES and ZEROES

In [210]:
zeroArray = np.zeros((5,6))
zeroArray

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [211]:
oneArray = np.ones((5,6))
oneArray

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [227]:
# MIN, MAX, MEAN, AVERAGE

In [218]:
a = np.array([[1,2,3,4,5],[6,7,8,9,0]])

In [219]:
a

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [220]:
a= a.flatten()

In [221]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [231]:
# Min
print(np.min(a))

0


In [232]:
# Max
print(np.max(a))

9


In [233]:
# Average
print(np.average(a))

4.5


In [234]:
# Mean
print(np.mean(a))

4.5


In [235]:
# Standard Deviation
print(np.std(a))

2.8722813232690143


In [236]:
# STD-> Mean is how far away from number whose mean is taken, Sum of all those values

In [238]:
# Expanding Dimension
print(np.expand_dims(a, axis = 0))
# An extra dimension will be added

[[1 2 3 4 5 6 7 8 9 0]]


In [239]:
print(np.expand_dims(a, axis = 1))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]
 [0]]
